jackdbus: fix link issues
similar to db4b99b5b6031fec3d20fc5b880b52d43917ecac
got broken by f94bf7174d155decbe7f483fea3fef056d66b104

For example jack_error was not linked properly:

jackdbus.c:(.text+0x36): undefined reference to `jack_error'

git-svn-id: http://subversion.jackaudio.org/jack/jack2/trunk/jackmp@4389 0c269be4-1314-0410-8aa9-9f06e86f4224