wscript: Fix undefined reference to jackd variable
If --classic isn't set, BUILD_JACKD == False, so jackd is not a valid
object. Hence, "jackd.source +=" does not work.