typecast input parameter to int for abs()
Fixes
../tests/test.cpp:482:73: error: call of overloaded 'abs(jack_nframes_t)' is ambiguous

because the signature is int abs(int) and its passing
unsigned int to it.

Signed-off-by: Khem Raj <raj.khem@gmail.com>