remove duplicate definition that causes compilation fail:
../common/jack/control.h:86:34: error: redefinition of typedef 'jackctl_parameter_t'
../common/jack/control.h:83:34: note: previous declaration of 'jackctl_parameter_t' was here

git-svn-id: http://subversion.jackaudio.org/jack/jack2/trunk/jackmp@4778 0c269be4-1314-0410-8aa9-9f06e86f4224