Remove not understood --c++11 brew install option
For OSX travis builds:
Since recently, brew install --c++11 stops the build.
Error: invalid option: --c++11
The command "./.ci/install-deps.sh" failed and exited with 1 during .
Your build has been stopped.